import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        {/* Contenedor de fondo */}
        <div className="relative min-h-screen bg-gradient-to-b from-slate-50 to-slate-100">
          {/* Imagen de fondo */}
          <div
            className="absolute inset-0 bg-cover bg-center opacity-60"
            style={{
              backgroundImage: "url('https://res.cloudinary.com/dxhi8xsyb/image/upload/v1731363405/propuesta2_mhnzja.jpg')",
            }}
          ></div>
          
          {/* Contenido principal con opacidad para asegurarse que es legible */}
          <div className="relative max-w-4xl mx-auto p-6 bg-white bg-opacity-90 shadow-lg">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
